[framework] 2019-12-16 21:27:42,583 - study.dao.UserDaoTest -4    [main] ERROR study.dao.UserDaoTest  - error: 进入了error
[framework] 2019-12-16 21:28:27,197 - study.dao.UserDaoTest -5    [main] ERROR study.dao.UserDaoTest  - error: 进入了error
